import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts"],
  format: ["esm"],
  // Declarations are generated by `tsc -p tsconfig.build.json` instead (see
  // the "build" script) — tsup's bundled rollup-plugin-dts is incompatible
  // with this repo's pinned TypeScript version.
  dts: false,
  sourcemap: true,
  clean: true,
  // React is a peer dependency, not bundled — consumers bring their own copy.
  external: ["react", "react-dom", "react/jsx-runtime"],
});
